title: "Astro Pi: Mission Zero"
hero_image: images/banner.png
description: Prepare for Mission Zero
listed: false
copyedit: true
version: 4.0.1
last_tested: 2018-06-12
steps:
- title: Introduction
- title: What is an Astro Pi?
- title: Display a message
- title: Add some colour
- title: Display an image
- title: Measure the Lighting conditions
- title: Display the Lighting conditions
- title: Challenge - Adjust LED brightness for the lighting conditions
- title: Submit your entry
- title: What next - more Astro Pi projects"
