title: "Astro Pi: Mission Zero"
hero_image: images/banner.png
description: Prepare for Mission Zero
listed: false
copyedit: true
version: 5.0.0
last_tested: 2018-06-12
steps:
- title: Introduction
- title: What is an Astro Pi?
- title: Display a message and choose the name of a new Astro Pi
- title: Add some colour
- title: Display an image
- title: Measure the humidity
- title: Reacting to humidity
- title: Submit your entry
- title: What next - more Astro Pi projects"
