---
title: "Astro Pi: Misión Cero"
hero_image: images/banner.png
description: Prepárate para Mission Zero
listed: false
copyedit: true
version: 5.0.0
last_tested: 2018-06-12
steps:
  - 
    title: Introducción
  - 
    title: '¿Qué es un Astro Pi?'
  - 
    title: Muestra un mensaje y elije un nombre para las nuevas computadoras Astro Pi
  - 
    title: Agrega un poco de color
  - 
    title: Muestra una imagen
  - 
    title: Mide la humedad
  - 
    title: Muestra la humedad
  - 
    title: Enviar tu proyecto
  - 
    title: 'Desafío: Más proyectos Astro Pi'
