---
title: "Astro Pi: Mission Zero"
hero_image: images/banner.png
description: Bereite dich auf Mission Zero vor
listed: false
copyedit: true
version: 5.0.0
last_tested: 2018-06-12
steps:
  - 
    title: Einleitung
  - 
    title: Was ist ein Astro Pi?
  - 
    title: Zeige eine Nachricht und wähle einen Namen für die neuen Astro Pi Computer
  - 
    title: Füge etwas Farbe hinzu
  - 
    title: Anzeigen eines Bildes
  - 
    title: Miss die Luftfeuchtigkeit
  - 
    title: Reagiere auf die Luftfeuchtigkeit
  - 
    title: Einreichen deines Beitrags
  - 
    title: Wie geht es weiter – weitere Astro Pi-Projekte"
