---
title: "Astro Pi: Αποστολή Μηδέν"
hero_image: images/banner.png
description: Προετοιμασία για την Αποστολή Μηδέν
listed: false
copyedit: true
version: 4.0.1
last_tested: 2017-06-01
steps:
  - 
    title: Introducció
  - 
    title: Τι είναι ένα Άστρο Πι?
  - 
    title: Εμφάνιση μηνύματος
  - 
    title: Add some colour
  - 
    title: Display an image
  - 
    title: Measure the humidity
  - 
    title: Display the humidity
  - 
    title: Submit your entry
  - 
    title: "Challenge: more Astro Pi projects"
