---
title: "Astro Pi: Mission Zero"
hero_image: images/banner.png
description: Připravte se na Mission Zero
listed: false
copyedit: true
version: 4.0.1
last_tested: 2017-06-01
steps:
  - title: Úvod
  - title: Co je Astro Pi?
  - title: Zobrazte zprávu
  - title: Přidejte barvy
  - title: Zobrazte obrázek
  - title: Změřte teplotu
  - title: Zobrazte teplotu
  - title: Odešlete svůj příspěvek
  - title: "Výzva: další projekty Astro Pi"
