---
title: "Astro Pi: Mission Zero"
hero_image: images/banner.png
description: Προετοιμαστείτε για το Mission Zero
listed: false
copyedit: true
version: 4.0.1
last_tested: 2018-06-12
steps:
  - title: Εισαγωγή
  - title: Τι είναι το Astro Pi
  - title: Εμφάνιση μηνύματος
  - title: Προσθέστε χρώμα
  - title: Εμφάνιση εικόνας
  - title: Μέτρηση της θερμοκρασίας
  - title: Εμφάνιση της θερμοκρασίας
  - title: Υποβάλετε την καταχώρησή σας
  - title: "Πρόκληση: περισσότερα έργα Astro Pi"
