---
title: "Astro Pi : Mission Zero"
hero_image: images/banner.png
description: Se préparer pour Mission Zero
listed: false
copyedit: true
version: 5.0.0
last_tested: 2018-06-12
steps:
  - 
    title: Introduction
  - 
    title: Qu'est-ce qu'un Astro Pi ?
  - 
    title: Afficher un message et choisir un nom pour les nouveaux ordinateurs Astro Pi
  - 
    title: Ajouter de la couleur
  - 
    title: Afficher une image
  - 
    title: Mesurer l'humidité
  - 
    title: Afficher l'humidité
  - 
    title: Soumettre ton programme
  - 
    title: Et ensuite — d'autres projets Astro Pi
