---
title: "Astro Pi: Mission Zéro"
hero_image: images/banner.png
description: Prépare-toi pour la Mission Zéro
listed: false
copyedit: true
version: 4.0.1
last_tested: 2018-06-12
steps:
  - 
    title: Introduction
  - 
    title: Qu'est-ce qu'un Astro Pi ?
  - 
    title: Afficher un message
  - 
    title: Ajouter de la couleur
  - 
    title: Afficher une image
  - 
    title: Mesurer la température
  - 
    title: Afficher la température
  - 
    title: Soumission de ta proposition
  - 
    title: "Défi: davantage de projets Astro Pi"
