---
title: "Astro Pi: Mission Zero"
hero_image: images/banner.png
description: Prépare-toi pour la Mission Zero
listed: false
copyedit: true
version: 4.0.1
last_tested: 2018-06-12
steps:
  - 
    title: Introduction
  - 
    title: Qu'est-ce qu'un Astro Pi ?
  - 
    title: Affiche un message
  - 
    title: Ajoute de la couleur
  - 
    title: Affiche une image
  - 
    title: Mesurer l'humidité
  - 
    title: Afficher l'humidité
  - 
    title: Envoie ton programme
  - 
    title: "Défi: davantage de projets Astro Pi"
